version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: swaply-app
    ports:
      - "80:80"
    environment:
      - VITE_COINGECKO_API_KEY=${VITE_COINGECKO_API_KEY}
    restart: unless-stopped

  # Development service for local development with hot reloading
  dev:
    image: node:20-alpine
    container_name: swaply-dev
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - VITE_COINGECKO_API_KEY=${VITE_COINGECKO_API_KEY}
    restart: unless-stopped

# Define a named volume for node_modules to improve performance
volumes:
  node_modules: